### PR TITLE
ENG-2526: Fix issue with redemption code look up returning a 404.

### PR DESCRIPTION
**Pull request by jsurdilla**
@jordan-brough It looks a JS file was accidentally removed from the asset pipeline in 8f71b20e5234222d307400dac9228242512b3ee1, which would explain the undefined GiftCards error earlier. This attaches an onSubmit listener on the form, which takes of sending the correct request method and URL.

### CODE REVIEW

**Comment by jordan-brough** [comment]
@jsurdilla nice find! Did you already confirm w/ @richardnuno that the removal was accidental?

**Comment by richardnuno** [comment]
@jordan-brough @jsurdilla sorry about that, totally accidental. I removed the `.js` file and created a new `.js.coffee` file but didn't bring over the `require_tree`. Thanks for fixing!

**Comment by jsurdilla** [comment]
@richardnuno , np, thanks for confirming. @jordan-brough , I'll merge if you think this is good to go.

**Comment by athal7** [comment]
given that these are split in solidus (store credit in core and gift card as an extension), is there anything special that needs to happen there? or will it be ok?

**Comment by jsurdilla** [comment]
@athal7 , it looks like the original changes haven't made it to solidus and virtual gift cards yet so I'm assuming we don't need to do anything for solidus.

**Comment by athal7** [comment]
@jsurdilla which original changes?

**Comment by athal7** [comment]
oh 8f71b20? @richardnuno are you planning to submit that up to solidus?

**Comment by richardnuno** [comment]
I've already submitted it to Solidus: https://github.com/solidusio/solidus/pull/148

**Comment by athal7** [comment]
@richardnuno cool, do you know if it introduces this same bug?

**Comment by jsurdilla** [comment]
@athal7 @richardnuno , I think we're safe. The file that was deleted now lives in solidus_virtual_gift_card  and it's still there.

**Comment by richardnuno** [comment]
I agree, since the file now lives on the extension we should be fine.

**Comment by athal7** [comment]
you may be right, as long as the install generator for virtual gift card includes that js into the project upon install

**Comment by athal7** [comment]
:+1:

**Comment by jsurdilla** [comment]
Also, just confirmed this to work in a sandbox.

**Pull request merged**
